#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
# Copyright 2021, Silicon Labs

# This script assigns a delegated IPv6 prefix obtained via DHCPv6 to tun0
#
# This script is designed to be called from dhclient-script (isc-dhcp-client).
# Just copy it to /etc/dhclient-exit-hooks.d/prefix_delegation to enable it.

add_prefix()
{
    # /init is waiting for the prefix info before to launch wsbrd. wsbrd is
    # going to configure tun0 accordingly to /tmp/dhcpv6pd.lease.
    echo "$1" > /tmp/dhcpv6pd.lease
}

change_prefix()
{
    # TODO: ask to wsbrd to advertise the new prefix
    :
}

del_prefix()
{
    # Right, we uplink router has probably died. If you have a backup border
    # router, you may want this border router stop to advertise. So the Wi-SUN
    # device will migrate to the backup border router.
    #
    # If it is not the case, let's continue to advertise the last known prefix.
    # So, with a bit of chance, we will get the same prefix when the uplink
    # router will get back.
    #
    # So, finally, just do nothing
    :
}

case $reason in
    BOUND6|EXPIRE6|REBIND6|REBOOT6|RENEW6)
        if [ -n "$old_ip6_prefix" -a -n "$new_ip6_prefix" ]; then
            if [ "$old_ip6_prefix" != "$new_ip6_prefix" ]; then
                change_prefix "$old_ip6_prefix" "$new_ip6_prefix"
            else
                add_prefix "$new_ip6_prefix"
            fi
        elif [ -n "$old_ip6_prefix" ]; then
            del_prefix "$old_ip6_prefix"
        elif [ -n "$new_ip6_prefix" ]; then
            add_prefix "$new_ip6_prefix"
        fi
    ;;
esac
