#!/bin/sh
# vim: set sw=4 expandtab:
#
# Licence: GPLv2
# Created: 2020-11-18 15:37:16+01:00
# Main authors:
#     - Jérôme Pouiller <jerome.pouiller@silabs.com>
#

die()
{
    echo "$@" >&2
    exit 1
}

print_usage()
{
    cat << EOF >&2
Usage: $1

Get traces from the Wi-SUN border router through the JTAG link.
EOF
    [ "$2" ] && exit $2
}

launch_openocd()
{
    IS_MANDATORY=$1
    cat << 'EOF' > /tmp/openocd-rtt.cfg
rtt setup 0x20001c00 0x04000 "SEGGER RTT"
rtt server start 1001 0
telnet_port 1002
gdb_port 1003
tcl_port 1004
init
rtt start
EOF
    openocd -d0 -f board/efm32.cfg -f /tmp/openocd-rtt.cfg &
    OPENOCD_PID=$!
    sleep 1
    [ -d /proc/$OPENOCD_PID ] || die "Cannot connect to JLink probe"
}

OPTS=$(getopt -l help -- h "$@") || exit 1
eval set -- "$OPTS"
while true; do
    case "$1" in
        -h|--help)
            print_usage $0
            exit 0
            ;;
        --)
            shift
            break
            ;;
    esac
done

case "$1" in
    "")
        ;;
    *)
        print_usage $0
        exit 1
esac

launch_openocd
exec telnet 127.0.0.1 1001
